title: Daniel Hardesty Lewis - Engineering Scientist Associate
description: 'Engineering Scientist Associate at the Texas Advanced Computing Center. Research: Source Data to Visualization of scientific software models; Equity-Oriented Models of land use decisions and applications; Containerized Computing on clusters, clouds, and grids'
url: https://danielhardestylewis.com

markdown: kramdown
enable-mathjax: yes

permalink: /blog/:title/

# Pagination
paginate: 8
paginate_path: /blog/page:num/

include:
  - _pages

# Google Ananlytics Tracker.
analytics: UA-338939-1

# scholar
scholar:
  sort_by: author
  group_by: year
  group_order: descending
  type_order: [article, inproceedings, phdthesis, techreport]
  bibliography_template: bib

collections:
  presentations:
    output: true
    permalink: /publications/presentations/:path/
  projects:
    output: true
    permalink: /projects/:path/

exclude:
  - .git

plugins:
  - jekyll-sitemap    # Adds sitemap to the website at /sitemap.xml
  - jekyll-feed       # Adds feed to the website at /feed.xml
  - jekyll-paginate   # Used for sorting posts by page numbers.
  - jekyll-seo-tag    # Adds all the important SEO meta tags by default.
  - jekyll-scholar
